layout_spectrum: 0.2677281526848674
typography_spectrum: 0.16765570268034935
color:
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
  brandStrength: 0.7727859984152019
  lightness: 0.29426549188792706
  saturation: 0.5489183813333511
  rhythmicContrast: 0.827631130348891
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: The First Draft
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The First Draft
description: A place for a geekling Mama.
purpose: []
