name: The First Draft
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#12111b'
    - '#9192b7'
    - '#777487'
    - '#564a54'
    - '#bcbcbc'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
