typography_spectrum: 0.33755
color:
  brandColors:
    - '#12111b'
    - '#9192b7'
    - '#777487'
    - '#564a54'
    - '#bcbcbc'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50481
analytics:
  google: null
  facebook: null
  twitter: null
name: The First Draft
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The First Draft
purpose: []
